models/Role.php
<?php


namespace bridgeinn\pluto\models;

use Yii;
use yii\base\ModelEvent;
use yii\helpers\ArrayHelper;

class Role extends Permission
{
    public $roleChildren = [];      // names
    public $rolesAvailable = [];    // [ name => name ]

    /**
     * @param bool $runValidation
     * @return bool
     * @throws \yii\base\Exception
     * @throws \Exception
     */
    public function save($runValidation = true)
    {
        $r = parent::save($runValidation);

        if ($r && $this->roleChildren) {
            $auth = Yii::$app->authManager;
            $item = $auth->getRole($this->name);

            foreach($this->roleChildren as $id) {
                $child = $auth->getRole($id);
                $auth->addChild($item, $child);
            }
        }
        return $r;
    }

    /**
     * @throws \Exception
     */
    public function delete()
    {
        $event = new ModelEvent();
        $this->trigger(self::EVENT_BEFORE_DELETE, $event);
        if ($event->isValid)  {
            $auth = Yii::$app->authManager;
            $role = $auth->getRole($this->name);
            $auth->remove($role);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        $r = parent::rules();
        $r[] = ['roleChildren', 'safe'];
        return $r;
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        $r = parent::attributeLabels();
        $r['permChildren'] = Yii::t('pluto', 'Permissions');
        $r['roleChildren'] = Yii::t('pluto', 'Included Roles');
        return $r;
    }

    /**
     * {@inheritdoc}
     */
    public function attributeHints()
    {
        return [
            'name' => Yii::t('pluto', 'The name of this Role, preferably a noun. There may be no other Role or Permission with this name.'),
            'description' => Yii::t('pluto', 'The description of this Role.'),
            'ruleName' => Yii::t('pluto', 'The Condition applying to this Role.'),
            'data' => Yii::t('pluto', 'The additional data associated with the Condition.'),
            'permChildren' => Yii::t('pluto', 'The Permissions belonging to this Role.'),
            'roleChildren' => Yii::t('pluto', 'This Role includes all of the selected Roles.')
        ];
    }

    /**
     * @param $id
     */
    protected function loadItem($id) {
        $auth = Yii::$app->authManager;
        $role = $auth->getRole($id);
        if ($role)  {
            $this->oldName = $id;
            $this->setAttributes((array) $role);
            $children = $auth->getChildren($id);
            foreach ($children as $id => $child)   {
                if ($child->type == yii\rbac\Role::TYPE_PERMISSION) $this->permChildren[] = $id;
                else $this->roleChildren[] = $id;
            }
        }
    }

    /**
     * @param $id
     */
    protected function loadAvailable($id)
    {
        $auth = Yii::$app->authManager;
        $this->permsAvailable = ArrayHelper::map($auth->getPermissions(), 'name', 'name');
        $this->rolesAvailable = ArrayHelper::map($auth->getRoles(), 'name', 'name');
        if (! is_null($id)) {
            ArrayHelper::remove($this->rolesAvailable, $id);     // Role can't be its own child
        }
    }

    /**
     * @return yii\rbac\Role|null
     */
    protected function getOrCreateItem()    {
        $auth = Yii::$app->authManager;
        return $this->isNew ? $auth->createRole($this->name) : $auth->getRole($this->oldName);
    }
}

controllers/PermissionController.php
<?php
/**
 * yii2-pluto
 * ----------
 * User management module for Yii2 framework
 * Version 1.0.0
 * Copyright (c) 2019
 * Sjaak Priester, Amsterdam
 * MIT License
 * https://github.com/sjaakp/yii2-pluto
 * https://sjaakpriester.nl
 */

namespace bridgeinn\pluto\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\data\ArrayDataProvider;
use yii\helpers\ArrayHelper;
use bridgeinn\pluto\models\Permission;

class PermissionController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'permissions' => ['manageRoles'],
                    ],
                ],
                'denyCallback' => [ 'bridgeinn\pluto\Module', 'accessDenied' ]
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ArrayDataProvider([
            'allModels' =>Yii::$app->authManager->getPermissions(),
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionCreate()
    {
        $model = new Permission();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
            'rules' => $this->getRules(),
        ]);
    }

    /**
     * @param $id
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionUpdate($id)
    {
        $model = new Permission($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        $rList = Yii::$app->authManager->getRoles();
        $roles = [];
        foreach ($rList as $role)   {
            $pnames = ArrayHelper::getColumn(Yii::$app->authManager->getPermissionsByRole($role->name), 'name');
            if (in_array($model->name, $pnames)) $roles[] = $role;
        }

        return $this->render('update', [
            'model' => $model,
            'rules' => $this->getRules(),
            'roles' => new ArrayDataProvider([
                'allModels' => $roles
            ])
        ]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws \Exception
     */
    public function actionDelete($id)
    {
        $model = new Permission($id);
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * @return array
     */
    protected function getRules()
    {
        return ArrayHelper::map(Yii::$app->authManager->getRules(), 'name', 'name');
    }
}

controllers/RoleController.php
<?php
/**
 * yii2-pluto
 * ----------
 * User management module for Yii2 framework
 * Version 1.0.0
 * Copyright (c) 2019
 * Sjaak Priester, Amsterdam
 * MIT License
 * https://github.com/sjaakp/yii2-pluto
 * https://sjaakpriester.nl
 */

namespace bridgeinn\pluto\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\data\ArrayDataProvider;
use yii\helpers\ArrayHelper;
use bridgeinn\pluto\models\Role;
use bridgeinn\pluto\models\User;

class RoleController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'permissions' => ['manageRoles'],
                    ],
                ],
                'denyCallback' => [ 'bridgeinn\pluto\Module', 'accessDenied' ]
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ArrayDataProvider([
            'allModels' =>Yii::$app->authManager->getRoles(),
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionCreate()
    {
        $model = new Role();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
            'rules' => $this->getRules(),
        ]);
    }

    /**
     * @param $id
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionUpdate($id)
    {
        $model = new Role($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        $userIds = Yii::$app->authManager->getUserIdsByRole($model->name);

        $users = new ActiveDataProvider([
            'query' => User::find()->where(['in', 'id', $userIds])
        ]);

        return $this->render('update', [
            'model' => $model,
            'rules' => $this->getRules(),
            'users' => $users
        ]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws \Exception
     */
    public function actionDelete($id)
    {
        $model = new Role($id);
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * @return array
     */
    protected function getRules()
    {
        return ArrayHelper::map(Yii::$app->authManager->getRules(), 'name', 'name');
    }
}

controllers/RuleController.php
<?php
/**
 * yii2-pluto
 * ----------
 * User management module for Yii2 framework
 * Version 1.0.0
 * Copyright (c) 2019
 * Sjaak Priester, Amsterdam
 * MIT License
 * https://github.com/sjaakp/yii2-pluto
 * https://sjaakpriester.nl
 */

namespace bridgeinn\pluto\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\FileHelper;
use yii\data\ArrayDataProvider;
use bridgeinn\pluto\models\Rule;

class RuleController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'permissions' => ['manageRoles'],
                    ],
                ],
                'denyCallback' => [ 'bridgeinn\pluto\Module', 'accessDenied' ]
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @return string
     * @throws \yii\base\InvalidConfigException
     * @throws \Exception
     */
    public function actionIndex()
    {
        $namespace = $this->module->ruleNamespace;

        $files = FileHelper::findFiles(Yii::getAlias('@' . str_replace('\\', '/', $namespace)), [ 'only' => ['*Rule.php'] ]);

        $fileRules = [];
        foreach ($files as $path)   {
            $rule = Yii::createObject($namespace . '\\' . basename($path, '.php'));
            $fileRules[$rule->name] = $rule;
        }

        $auth = Yii::$app->authManager;

        $unregistered = array_diff_key($fileRules, $auth->getRules());

        if (Yii::$app->request->isPost) {
            foreach($unregistered as $rule) {
                /* @var $rule yii\rbac\Rule */
                $auth->add($rule);
            }
            $unregistered = [];
        }

        $regData = new ArrayDataProvider([
            'allModels' => $auth->getRules(),
        ]);
        $unregData = new ArrayDataProvider([
            'allModels' => $unregistered,
        ]);
        return $this->render('index', [
            'regData' => $regData,
            'unregData' => $unregData,
        ]);
    }

    /**
     * Deletes Rule from RBAC-system, does not delete Rule's class file
     * @param $id
     * @return \yii\web\Response
     * @throws \Exception
     */
    public function actionDelete($id)
    {
        $model = new Rule($id);
        $model->delete();

        return $this->redirect(['index']);
    }
}

controllers/UserController.php
<?php
/**
 * yii2-pluto
 * ----------
 * User management module for Yii2 framework
 * Version 1.0.0
 * Copyright (c) 2019
 * Sjaak Priester, Amsterdam
 * MIT License
 * https://github.com/sjaakp/yii2-pluto
 * https://sjaakpriester.nl
 */

namespace bridgeinn\pluto\controllers;

use bridgeinn\pluto\Module;
use Yii;
use bridgeinn\pluto\models\User;
use bridgeinn\pluto\models\UserSearch;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'permissions' => ['manageUsers'],
                    ],
                ],
                'denyCallback' => [ 'bridgeinn\pluto\Module', 'accessDenied' ]
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->sort->defaultOrder = ['name' => SORT_ASC];

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'defaultRoles' => $this->getDefaultRoles(),
        ]);
    }

    /**
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionCreate()
    {
        /* @var $module Module */
        $module = $this->module;

        $roles = $module->defaultRole;
        if (empty($roles)) $roles = [];
        if (is_string($roles)) $roles = [$roles];
        $model = new User([
            'scenario' => 'create',
            'status' => User::STATUS_ACTIVE,
            'roles' => $roles
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
            'roles' => $this->getRoles(),
            'defaultRoles' => $this->getDefaultRoles(),
        ]);
    }

    /**
     * @param $id
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionUpdate($id)
    {
        $model = $this->findAndCheckModel($id, Yii::t('pluto', 'update'));
        if (! $model) return $this->redirect(['index']);

        $model->scenario = 'update';

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                return $this->redirect(['index']);
            }
            // if error, updated_at may be 'NOW()', which DetailView doesn't understand
            $model->updated_at = $model->getOldAttribute('updated_at');
        }

        return $this->render('update', [
            'model' => $model,
            'roles' => $this->getRoles(),
            'defaultRoles' => $this->getDefaultRoles(),
        ]);
    }

    /**
     * @return array of Role name => Role name
     */
    protected function getRoles()
    {
        return ArrayHelper::map(Yii::$app->authManager->getRoles(), 'name', 'name');
    }

    /**
     * @return array of Role name
     */
    protected function getDefaultRoles()
    {
        /* @var $auth yii\rbac\BaseManager */
        $auth = Yii::$app->authManager;
        return $auth->getDefaultRoles();
    }

    /**
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \yii\db\Exception
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $model = $this->findAndCheckModel($id, Yii::t('pluto', 'delete'));
        if ($model) $model->delete();
        return $this->redirect(['index']);
    }

    /**
     * @param $id
     * @param $verb
     * @return User|null
     * @throws NotFoundHttpException
     */
    protected function findAndCheckModel($id, $verb)
    {
        $model = $this->findModel($id);
        if (! Yii::$app->user->can('updateUser', $model))   {
            Yii::$app->session->setFlash('danger', Yii::t('pluto',
                'Sorry {username}, you\'re not allowed to {verb} <strong>{goal}</strong>\'s user data.', [
                    'verb' => $verb,
                    'username' => Yii::$app->user->identity->name ?? '',
                    'goal' => $model->name ?? ''
                ]));
            return null;
        }
        return $model;
    }

    /**
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('pluto', Yii::t('pluto', 'The requested User does not exist.')));
    }
}

views/role/_form.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model bridgeinn\pluto\models\Role */
/* @var $rules array */
/* @var $context yii\web\Controller */
/* @var $form yii\widgets\ActiveForm */

$context = $this->context;
$module = $context->module;
$viewOptions = $module->viewOptions;
?>
<?php $form = $module->formClass::begin(); ?>

<?= $form->field($model, 'name')->textInput([ 'autofocus' => true ]) ?>

<?= $form->field($model, 'description')->textInput() ?>

<div class="row mb-3">
    <?= $form->field($model, 'ruleName', [ 'options' => ['class' => 'col-3']])->dropDownList($rules, [
        'prompt' => ''
    ]) ?>
</div>

<!--<?/*= $form->field($model, 'data')->textInput() */?>-->

<?= $this->render('/partials/dualList', [
    'form' => $form,
    'model' => $model,
    'attribute' => 'roleChildren',
    'items' => $model->rolesAvailable
]) ?>

<?= $this->render('/partials/dualList', [
    'form' => $form,
    'model' => $model,
    'attribute' => 'permChildren',
    'items' => $model->permsAvailable
]) ?>

<div class="form-group">
    <?= Html::submitButton(Yii::t('pluto', 'Save'), $viewOptions['button']) ?>
</div>

<?php $module->formClass::end(); ?>

views/role/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model bridgeinn\pluto\models\Role */
/* @var $rules array */

$this->title = Yii::t('pluto', 'New Role');
$this->params['breadcrumbs'][] = ['label' => Yii::t('pluto', 'Roles'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<h1><?= Html::encode($this->title) ?></h1>

<?= $this->render('_form', [
    'model' => $model,
    'rules' => $rules
]) ?>

views/role/index.php
<?php
/**
 * yii2-pluto
 * ----------
 * User management module for Yii2 framework
 * Version 1.0.0
 * Copyright (c) 2019
 * Sjaak Priester, Amsterdam
 * MIT License
 * https://github.com/sjaakp/yii2-pluto
 * https://sjaakpriester.nl
 */

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\BaseDataProvider */
/* @var $context yii\web\Controller */

/* @link https://github.com/softark/yii2-dual-listbox */

$context = $this->context;
$viewOptions = $context->module->viewOptions;

$this->title = Yii::t('pluto', 'Roles');
$this->params['breadcrumbs'][] = $this->title;
?>
<h1><?= $this->title ?></h1>

<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        [
            'class' => 'yii\grid\SerialColumn',
            'contentOptions' => [ 'class' => 'text-info' ]
        ],

        [
            'attribute' => 'name',
            'label' => Yii::t('pluto', 'Name'),
            'content' => function($model, $key, $index, $widget)    {
                return Html::a($model->name, [ 'update', 'id' => $model->name ]);
            },
            'format' => 'html',
        ],
        'description:text:' . Yii::t('pluto', 'Description'),
        'ruleName:text:' . Yii::t('pluto', 'Condition'),
//        'data',
//        'createdAt:datetime',
//        'updatedAt:datetime',

        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{update} {delete}'
        ],
    ],
    'formatter' => [
        'class' => 'yii\i18n\Formatter',
        'datetimeFormat' => 'short', // 'dd-MM-yyyy HH:mm:ss'
        'nullDisplay' => '',
    ],
    'tableOptions' => ['class' => 'table table-sm table-bordered'],
    'summary' => '<div class="small text-info">{begin}-{end}/{totalCount}</div>',
    'emptyText' => Yii::t('pluto', 'none'),
    'emptyTextOptions' => [ 'class' => 'small text-info'],
]); ?>

<p><?= Html::a(Yii::t('pluto', 'New Role'), ['create'], $viewOptions['button']) ?>
 <?= Html::a(Yii::t('pluto', 'Permissions'), ['permission/index'], $viewOptions['link']) ?>
 <?= Html::a(Yii::t('pluto', 'Conditions'), ['rule/index'], $viewOptions['link']) ?>
</p>

views/role/update.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $model bridgeinn\pluto\models\Role */
/* @var $rules array */
/* @var $users yii\data\ActiveDataProvider */

$this->title = Yii::t('pluto', 'Update Role: {rolename}', [
    'rolename' => $model->name
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('pluto', 'Roles'), 'url' => ['index']];
$this->params['breadcrumbs'][] = Yii::t('pluto', 'Update {rolename}', [
    'rolename' => $model->name
]);
?>
<h1><?= Html::encode($this->title) ?></h1>

<?= $this->render('_form', [
    'model' => $model,
    'rules' => $rules
]) ?>

<hr />
<?= DetailView::widget([
    'model' => $model,
    'attributes' => [
        'createdAt:datetime',
        'updatedAt:datetime',
    ],
    'options' => [
        'tag' => 'dl',
        'class' => 'dl-horizontal small text-muted'
    ],
    'template' => '<dt>{label}</dt><dd>{value}</dd>',
    'formatter' => [
        'class' => 'yii\i18n\Formatter',
        'datetimeFormat' => 'short'
    ],
]) ?>

<h4><small><?= Yii::t('pluto', 'Users with this Role') ?></small></h4>
<?= ListView::widget([
    'dataProvider' => $users,
    'itemView' => function ($model, $key, $index, $widget) {
        return Html::a($model->name, ['user/update', 'id' => $model->id]);
    },
    'summary' => '<div class="small text-info">{begin}-{end}/{totalCount}</div>',
    'emptyText' => Yii::t('pluto', 'none'),
    'emptyTextOptions' => [ 'class' => 'small text-info'],
]) ?>