models/Permission.php
<?php
/**
 * yii2-pluto
 * ----------
 * User management module for Yii2 framework
 * Version 1.0.0
 * Copyright (c) 2019
 * Sjaak Priester, Amsterdam
 * MIT License
 * https://github.com/sjaakp/yii2-pluto
 * https://sjaakpriester.nl
 */

namespace bridgeinn\pluto\models;

use Yii;
use yii\base\Model;
use yii\base\ModelEvent;
use yii\helpers\ArrayHelper;

class Permission extends Model
{
    const EVENT_BEFORE_SAVE = 'beforeSave';
    const EVENT_BEFORE_DELETE = 'beforeDelete';

    public $name;
    public $description;
    public $ruleName;
    public $data;
    public $createdAt;
    public $updatedAt;

    public $permChildren = [];      // names
    public $permsAvailable = [];    // [ name => name ]

    protected $oldName;

    /**
     * Permission constructor.
     * @param null $id
     * @param array $config
     */
    public function __construct($id = null, $config = [])
    {
        if (! is_null($id))   {
            $this->loadItem($id);
        }
        $this->loadAvailable($id);
        parent::__construct($config);
    }

    /**
     * @return bool
     */
    public function getIsNew()
    {
        return is_null($this->oldName);
    }

    /**
     * @param bool $runValidation
     * @return bool
     * @throws \yii\base\Exception
     * @throws \Exception
     */
    public function save($runValidation = true)
    {
        $event = new ModelEvent();
        $this->trigger(self::EVENT_BEFORE_SAVE, $event);
        if (! $event->isValid)  {
            return false;
        }

        if ($runValidation && !$this->validate()) {
            return false;
        }

        $auth = Yii::$app->authManager;

        $item = $this->getOrCreateItem();
        if (! $this->isNew) $auth->removeChildren($item);

        $item->name = $this->name;
        $item->description = $this->description;
        $item->ruleName = $this->ruleName;
        $item->data = $this->data;

        if ($this->isNew) $auth->add($item);
        else $auth->update($this->oldName, $item);

        if ($this->permChildren) {
            foreach($this->permChildren as $id) {
                $child = $auth->getPermission($id);
                $auth->addChild($item, $child);
            }
        }
        return true;
    }

    /**
     * @throws \Exception
     */
    public function delete()
    {
        $event = new ModelEvent();
        $this->trigger(self::EVENT_BEFORE_DELETE, $event);
        if ($event->isValid)  {
            $auth = Yii::$app->authManager;
            $perm = $auth->getPermission($this->name);
            $auth->remove($perm);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'description', 'ruleName', 'data' ], 'string'],
            ['ruleName', 'default', 'value' => null],  // without this, integrity violation with DbManager, nasty!
            ['name', 'validateName'],
            [['createdAt', 'updatedAt'], 'safe'],
            ['permChildren', 'safe']
        ];
    }

    /**
     * Validates name.
     * Documentation states that name must be 'globally unique'.
     * I gather that this means that no Item (Role or Permission) can have the same name.
     * @link https://www.yiiframework.com/doc/api/2.0/yii-rbac-item#$name-detail
     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validateName($attribute, $params)
    {
        if (!$this->hasErrors() && $this->$attribute != $this->oldName) {
            $auth = Yii::$app->authManager;
            if ($auth->getRole($this->$attribute) || $auth->getPermission($this->$attribute))   {
                $this->addError($attribute, "The name '{$this->$attribute}' is already taken.");
            }
        }
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'name' => Yii::t('pluto', 'Name'),
            'description' => Yii::t('pluto', 'Description'),
            'ruleName' => Yii::t('pluto', 'Condition'),
            'permChildren' => Yii::t('pluto', 'Included Permissions'),
            'createdAt' => Yii::t('pluto', 'Created at'),
            'updatedAt' => Yii::t('pluto', 'Updated at'),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeHints()
    {
        return [
            'name' => Yii::t('pluto', 'The name of this Permission, preferably a verb. There may be no other Role or Permission with this name.'),
            'description' => Yii::t('pluto', 'The description of this Permission.'),
            'ruleName' => Yii::t('pluto', 'The Condition applying to this Permission.'),
            'data' => Yii::t('pluto', 'The additional data associated with the Condition.'),
            'permChildren' => Yii::t('pluto', 'This Permission includes all of the selected Permissions.')
        ];
    }

    /**
     * @param $id
     */
    protected function loadItem($id) {
        $auth = Yii::$app->authManager;
        $perm = $auth->getPermission($id);
        if ($perm)  {
            $this->oldName = $id;
            $this->setAttributes((array) $perm);
            $this->permChildren = array_keys($auth->getChildren($id));
        }
    }

    /**
     * @param $id
     */
    protected function loadAvailable($id)
    {
        $auth = Yii::$app->authManager;
        $this->permsAvailable = ArrayHelper::map($auth->getPermissions(), 'name', 'name');
        if (! is_null($id)) {
            ArrayHelper::remove($this->permsAvailable, $id);     // Permission can't be its own child
        }
    }

    /**
     * @return yii\rbac\Permission|null
     */
    protected function getOrCreateItem()    {
        $auth = Yii::$app->authManager;
        return $this->isNew ? $auth->createPermission($this->name) : $auth->getPermission($this->oldName);
    }
}

controllers/PermissionController.php
<?php
/**
 * yii2-pluto
 * ----------
 * User management module for Yii2 framework
 * Version 1.0.0
 * Copyright (c) 2019
 * Sjaak Priester, Amsterdam
 * MIT License
 * https://github.com/sjaakp/yii2-pluto
 * https://sjaakpriester.nl
 */

namespace bridgeinn\pluto\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\data\ArrayDataProvider;
use yii\helpers\ArrayHelper;
use bridgeinn\pluto\models\Permission;

class PermissionController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'permissions' => ['manageRoles'],
                    ],
                ],
                'denyCallback' => [ 'bridgeinn\pluto\Module', 'accessDenied' ]
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ArrayDataProvider([
            'allModels' =>Yii::$app->authManager->getPermissions(),
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionCreate()
    {
        $model = new Permission();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
            'rules' => $this->getRules(),
        ]);
    }

    /**
     * @param $id
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionUpdate($id)
    {
        $model = new Permission($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        $rList = Yii::$app->authManager->getRoles();
        $roles = [];
        foreach ($rList as $role)   {
            $pnames = ArrayHelper::getColumn(Yii::$app->authManager->getPermissionsByRole($role->name), 'name');
            if (in_array($model->name, $pnames)) $roles[] = $role;
        }

        return $this->render('update', [
            'model' => $model,
            'rules' => $this->getRules(),
            'roles' => new ArrayDataProvider([
                'allModels' => $roles
            ])
        ]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws \Exception
     */
    public function actionDelete($id)
    {
        $model = new Permission($id);
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * @return array
     */
    protected function getRules()
    {
        return ArrayHelper::map(Yii::$app->authManager->getRules(), 'name', 'name');
    }
}

controllers/RoleController.php
<?php
/**
 * yii2-pluto
 * ----------
 * User management module for Yii2 framework
 * Version 1.0.0
 * Copyright (c) 2019
 * Sjaak Priester, Amsterdam
 * MIT License
 * https://github.com/sjaakp/yii2-pluto
 * https://sjaakpriester.nl
 */

namespace bridgeinn\pluto\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\data\ArrayDataProvider;
use yii\helpers\ArrayHelper;
use bridgeinn\pluto\models\Role;
use bridgeinn\pluto\models\User;

class RoleController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'permissions' => ['manageRoles'],
                    ],
                ],
                'denyCallback' => [ 'bridgeinn\pluto\Module', 'accessDenied' ]
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ArrayDataProvider([
            'allModels' =>Yii::$app->authManager->getRoles(),
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionCreate()
    {
        $model = new Role();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
            'rules' => $this->getRules(),
        ]);
    }

    /**
     * @param $id
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionUpdate($id)
    {
        $model = new Role($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        $userIds = Yii::$app->authManager->getUserIdsByRole($model->name);

        $users = new ActiveDataProvider([
            'query' => User::find()->where(['in', 'id', $userIds])
        ]);

        return $this->render('update', [
            'model' => $model,
            'rules' => $this->getRules(),
            'users' => $users
        ]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws \Exception
     */
    public function actionDelete($id)
    {
        $model = new Role($id);
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * @return array
     */
    protected function getRules()
    {
        return ArrayHelper::map(Yii::$app->authManager->getRules(), 'name', 'name');
    }
}

views/permission/_form.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model bridgeinn\pluto\models\Permission */
/* @var $rules array */
/* @var $context yii\web\Controller */
/* @var $form yii\widgets\ActiveForm */

$context = $this->context;
$module = $context->module;
$viewOptions = $module->viewOptions;
?>
<?php $form = $module->formClass::begin(); ?>

<?= $form->field($model, 'name')->textInput([ 'autofocus' => true ]) ?>

<?= $form->field($model, 'description')->textInput() ?>

<div class="row mb-3">
    <?= $form->field($model, 'ruleName', [ 'options' => ['class' => 'col-3']])->dropDownList($rules, [
        'prompt' => ''
    ]) ?>
</div>

<!--<?/*= $form->field($model, 'data')->textInput() */?>-->

<?= $this->render('/partials/dualList', [
    'form' => $form,
    'model' => $model,
    'attribute' => 'permChildren',
    'items' => $model->permsAvailable
]) ?>

<div class="form-group">
    <?= Html::submitButton(Yii::t('pluto', 'Save'), $viewOptions['button']) ?>
</div>

<?php $module->formClass::end(); ?>

views/permission/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model bridgeinn\pluto\models\Permission */
/* @var $rules array */

$this->title = Yii::t('pluto', 'New Permission');
$this->params['breadcrumbs'][] = ['label' => Yii::t('pluto', 'Roles'), 'url' => ['role/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('pluto', 'Permissions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<h1><?= Html::encode($this->title) ?></h1>

<?= $this->render('_form', [
    'model' => $model,
    'rules' => $rules
]) ?>

views/permission/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\BaseDataProvider */
/* @var $context yii\web\Controller */

/* @link https://github.com/softark/yii2-dual-listbox */

$context = $this->context;
$viewOptions = $context->module->viewOptions;

$this->title = Yii::t('pluto', 'Permissions');
$this->params['breadcrumbs'][] = ['label' => Yii::t('pluto', 'Roles'), 'url' => ['role/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<h1><?= $this->title ?></h1>

<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        [
            'class' => 'yii\grid\SerialColumn',
            'contentOptions' => [ 'class' => 'text-info' ]
        ],

        [
            'attribute' => 'name',
            'label' => Yii::t('pluto', 'Name'),
            'content' => function($model, $key, $index, $widget)    {
                return Html::a($model->name, [ 'update', 'id' => $model->name ]);
            },
            'format' => 'html',
        ],
        'description:text:' . Yii::t('pluto', 'Description'),
        'ruleName:text:' . Yii::t('pluto', 'Condition'),
//        'data',
//        'createdAt:datetime',
//        'updatedAt:datetime',

        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{update} {delete}'
        ],
    ],
    'formatter' => [
        'class' => 'yii\i18n\Formatter',
        'datetimeFormat' => 'short', // 'dd-MM-yyyy HH:mm:ss'
        'nullDisplay' => '',
    ],
    'tableOptions' => ['class' => 'table table-sm table-bordered'],
    'summary' => '<div class="small text-info">{begin}-{end}/{totalCount}</div>',
    'emptyText' => Yii::t('pluto', 'none'),
    'emptyTextOptions' => [ 'class' => 'small text-info'],
]); ?>

<p><?= Html::a(Yii::t('pluto', 'New Permission'), ['create'], $viewOptions['button']) ?></p>

views/permission/update.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $model bridgeinn\pluto\models\Permission */
/* @var $rules array */
/* @var $roles array */

$this->title = Yii::t('pluto', 'Update Permission: {permissionname}', [
    'permissionname' => $model->name
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('pluto', 'Roles'), 'url' => ['role/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('pluto', 'Permissions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = Yii::t('pluto', 'Update {permissionname}', [
    'permissionname' => $model->name
]);

?>
<h1><?= Html::encode($this->title) ?></h1>

<?= $this->render('_form', [
    'model' => $model,
    'rules' => $rules
]) ?>

<?= DetailView::widget([
    'model' => $model,
    'attributes' => [
        'createdAt:datetime',
        'updatedAt:datetime',
    ],
    'options' => [
        'tag' => 'dl',
        'class' => 'dl-horizontal small text-muted'
    ],
    'template' => '<dt>{label}</dt><dd>{value}</dd>',
    'formatter' => [
        'class' => 'yii\i18n\Formatter',
        'datetimeFormat' => 'short'
    ],
]) ?>

<h4><small><?= Yii::t('pluto', 'Roles with this Permission') ?></small></h4>
<?= ListView::widget([
    'dataProvider' => $roles,
    'itemView' => function ($model, $key, $index, $widget) {
        return Html::a($model->name, ['role/update', 'id' => $model->name]);
    },
    'summary' => '<div class="small text-info">{begin}-{end}/{totalCount}</div>',
    'emptyText' => Yii::t('pluto', 'none'),
    'emptyTextOptions' => [ 'class' => 'small text-info'],
]) ?>